# Generated by Django 2.2.5 on 2019-09-25 18:07

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ban_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
